apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  annotations: {{- range $k, $v := .Values.ingress.annotations }}
    {{$k}}: {{ . | toYaml | indent 4 | trim }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.baseHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}-service
                port:
                  number: {{ .Values.app.servicePort }}