kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.db.volume.name }} # Sets PV's name
  labels:
    type: {{ .Values.db.volume.type }}
    app: {{ .Values.db.label }}
spec:
  storageClassName: {{ .Values.db.volume.storageClassName }}
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: {{ .Values.db.volume.size }} # Sets PV Volume
  accessModes: {{ .Values.db.volume.accessModes }}
  hostPath:
    path: {{ .Values.db.volume.hostPath }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.db.volume.name }}-claim # Sets name of PVC
  labels:
    app: {{ .Values.db.label }}
spec:
  storageClassName: {{ .Values.db.volume.storageClassName }}
  accessModes: {{ .Values.db.volume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.db.volume.size }}  # Sets volume size