apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  selector:
    app: {{ .Values.app.name }} #the app label that service should listen to
  ports:
  - protocol: TCP
    port: 8080 #the port that will be exposed by the service
    targetPort: 8000 #the port that service should listen to
  type: ClusterIP