{
 "title": "HW Dashboard",
 "time": { "from": "now-90m", "to": "now-1h" },
 "refresh": "5s",
 "panels": [
  { "title": "APP Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Response time Q0.5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le, path) (rate(http_response_time_seconds_bucket{path=~\"/users/.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time Q0.95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(http_response_time_seconds_bucket{path=~\"/users/.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time Q0.99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, path) (rate(http_response_time_seconds_bucket{path=~\"/users/.*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time MAX",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (path) (rate(http_response_time_seconds_bucket{path=~\"/users/.*\", statusCode=~\"2..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (rate(http_response_time_seconds_bucket{path=~\"/users/.*\", statusCode=~\"5..\"}[2m])) / sum by(path) (rate(http_response_time_seconds_bucket{path=~\"/users/.*\"}[2m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total{path=~\"/users/.*\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total[1m])) / sum (machine_cpu_cores) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"apiserver\"} / 1024 ^ 2",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}