app:
  name: homework-app
  baseHost: arch.homework
  port: 8000
  portName: web
  servicePort: 8080
  serviceProtocol: TCP
  image: russbalabanov/docker-homework:v3
  liveness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 15
    failureThreshold: 1
  deployment:
    replicas: 3
    update:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

db:
  image: postgres:14-alpine #Not the latest version, but pretty stable
  secretName: db-root-password
  port: 5432
  label: postgres
  cfgName:  postgres-config
  name: app

  service:
    name: app-db-service
    port: 5355
    externalPort: 32355

  volume:
    type: local # Sets PV's type to local
    storageClassName: manual
    size: 2Gi
    name: pg-pv
    hostPath: /mnt/db
    accessModes:
      - ReadWriteMany
    mount:
      path: /var/lib/postgresql/data
      name: postgresdb

migrations:
  name: migration-job
  image: russbalabanov/hw-migrations:v1
  ttlSecondsAfterFinished: 10
  restartPolicy: Never
  backoffLimit: 4

ingress:
  annotations:
    nginx.org/server-snippets: |
      location = /otusapp/ruslan_balabanov {
         rewrite ^ /health;
      }
